"""Build compact province outlines for the mini program.

Input: China-GeoData/geojson/china_province_full.geojson (MIT)
https://github.com/Supeset/China-GeoData
Run: python3 scripts/build-province-boundaries.py /path/to/china_province_full.geojson

The source is an AMap-style GeoJSON. Keep its native coordinates to align with
the Tencent map's GCJ-02 China tiles. The result is a visual guide, not a
survey-grade boundary or a substitute for an official map.
"""

import json
import sys
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "miniprogram/data/province-boundaries.json"
MODULE_OUTPUT = OUTPUT.with_suffix(".ts")


def distance_sq(point, start, end):
    dx, dy = end[0] - start[0], end[1] - start[1]
    if dx == dy == 0:
        return (point[0] - start[0]) ** 2 + (point[1] - start[1]) ** 2
    t = max(0, min(1, ((point[0] - start[0]) * dx + (point[1] - start[1]) * dy) / (dx * dx + dy * dy)))
    return (point[0] - start[0] - t * dx) ** 2 + (point[1] - start[1] - t * dy) ** 2


def simplify(points, tolerance=0.045):
    points = points[:-1] if points[0] == points[-1] else points
    if len(points) <= 3:
        return points
    # Split the closed ring at its most distant vertex so both halves retain shape.
    anchor = max(range(1, len(points)), key=lambda i: distance_sq(points[i], points[0], points[-1]))

    def section(items):
        if len(items) <= 2:
            return items
        index = max(range(1, len(items) - 1), key=lambda i: distance_sq(items[i], items[0], items[-1]))
        if distance_sq(items[index], items[0], items[-1]) <= tolerance * tolerance:
            return [items[0], items[-1]]
        return section(items[: index + 1])[:-1] + section(items[index:])

    reduced = section(points[: anchor + 1])[:-1] + section(points[anchor:])
    return reduced if len(reduced) >= 3 else points[:3]


def area(ring):
    return abs(sum(a[0] * b[1] - b[0] * a[1] for a, b in zip(ring, ring[1:] + ring[:1]))) / 2


def main():
    if len(sys.argv) != 2:
        raise SystemExit("Pass the source GeoJSON path")
    source = json.loads(Path(sys.argv[1]).read_text())
    result = {}
    for feature in source["features"]:
        name = feature["properties"].get("name", "")
        if not isinstance(feature["properties"].get("adcode"), int):
            continue  # Exclude decorative nine-dash-line geometry.
        geometry = feature["geometry"]
        polygons = geometry["coordinates"] if geometry["type"] == "MultiPolygon" else [geometry["coordinates"]]
        rings = sorted((polygon[0] for polygon in polygons), key=area, reverse=True)
        # Keep the mainland/main island plus meaningful outlying islands.
        selected = [ring for ring in rings if area(ring) >= 0.00035][:10] or rings[:1]
        result[name] = [
            [[round(lng, 5), round(lat, 5)] for lng, lat in simplify(ring)]
            for ring in selected
        ]
    serialized = json.dumps(result, ensure_ascii=False, separators=(",", ":"))
    OUTPUT.write_text(serialized + "\n")
    # WeChat's TypeScript compiler does not package a JSON file imported from a
    # script module. Keep a TypeScript copy that the mini program can require.
    MODULE_OUTPUT.write_text(
        "// Generated by scripts/build-province-boundaries.py; do not edit by hand.\n"
        "const boundaries: Record<string, [number, number][][]> = " + serialized + "\n"
        "export default boundaries\n"
    )
    print(f"{len(result)} provinces, {OUTPUT.stat().st_size} bytes -> {OUTPUT}, {MODULE_OUTPUT}")


if __name__ == "__main__":
    main()
